apps:
- name: helm-argocd-apps
  namespace: argocd
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-argocd-apps.git
    path: charts/argocd-apps

# Cluster apps
- name: k8s-dashboard
  namespace: kubernetes-dashboard
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/k8s-dashboard

- name: metallb-sys
  namespace: metallb-system
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/metallb-sys
- name: metallb-conf
  namespace: metallb-system
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/metallb-conf
- name: cert-manager
  namespace: cert-manager
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/cert-manager
- name: ingress-nginx
  namespace: ingress
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/ingress-nginx
#- name: vault
#  namespace: vault
#  valueFiles:
#    - values_td-rke.yaml
#  repo:
#    url: https://github.com/marksie1988-iac/helm-vault.git
#    path: .



# User Apps

- name: excalidraw
  namespace: prd
  valueFiles:
    - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-apps.git
    path: charts/excalidraw
