apps:
- name: argocd-apps
  namespace: argocd
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-argocd-apps.git
    path: charts/argocd-apps

# Cluster apps
- name: k8s-dashboard
  namespace: kubernetes-dashboard
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/k8s-dashboard

- name: cert-manager
  namespace: cert-manager
  valueFiles:
  - values_td-rke.yaml
  repo:
    url: https://github.com/marksie1988-iac/helm-cluster.git
    path: charts/cert-manager
